# Generated by Django 5.2.5 on 2025-08-21 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmedia',
            options={'verbose_name': 'Report Media', 'verbose_name_plural': 'Report Media'},
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
