# Generated by Django 5.2.5 on 2025-08-20 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('country', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=25)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(choices=[('gps', 'GPS'), ('manual', 'Manual')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'location',
            },
        ),
    ]
